const target = new Date('2026-12-19T10:00:00+07:00').getTime();
const ids = ['d','h','m','s'];
const progressBar=document.getElementById('progressBar');
setInterval(()=>{const now=Date.now();const diff=Math.max(0,target-now);const d=Math.floor(diff/86400000),h=Math.floor(diff%86400000/3600000),m=Math.floor(diff%3600000/60000),s=Math.floor(diff%60000/1000);[d,h,m,s].forEach((v,i)=>document.getElementById(ids[i]).textContent=String(v).padStart(2,'0'));},1000);
window.addEventListener('scroll',()=>{const h=document.documentElement;const sc=(h.scrollTop)/(h.scrollHeight-h.clientHeight||1)*100;progressBar.style.width=sc+'%';});
const bgm=document.getElementById('bgm'), musicBtn=document.getElementById('musicBtn');
musicBtn.onclick=async()=>{try{if(bgm.paused){await bgm.play();musicBtn.textContent='♪ Pause'}else{bgm.pause();musicBtn.textContent='♪ Musik'}}catch(e){alert('Browser memblokir autoplay. Klik lagi untuk memulai musik.')}};
document.getElementById('enterBtn').onclick=()=>document.getElementById('intro').classList.add('hide');
document.getElementById('topBtn').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});
const reveals=document.querySelectorAll('.reveal');
const io=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show');});},{threshold:.15});
reveals.forEach(el=>io.observe(el));
const waBtn=document.getElementById('waBtn');
waBtn.onclick=()=>{
  const name=document.getElementById('rsvpName').value.trim()||'Tamu Undangan';
  const count=document.getElementById('rsvpCount').value.trim()||'1';
  const msg=document.getElementById('rsvpMsg').value.trim()||'Hadir';
  const text=encodeURIComponent(`Halo, saya ${name}. Jumlah tamu: ${count}. Pesan: ${msg}`);
  waBtn.href=`https://wa.me/620881081912121?text=${text}`;
};
